from BaseClasses import Location
from typing import Dict
from . import names


class NuclearThroneLocation(Location):
    game = "Nuclear Throne"


fish_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_fish}" :     11001,
    f"{names.desert_02} - {names.char_fish}" :     12001,
    f"{names.desert_03} - {names.char_fish}" :     13001,
    f"{names.sewers} - {names.char_fish}" :        11002,
    f"{names.scrapyard_01} - {names.char_fish}" :  11003,
    f"{names.scrapyard_02} - {names.char_fish}" :  12003,
    f"{names.scrapyard_03} - {names.char_fish}" :  13003,
    f"{names.caves} - {names.char_fish}" :         11004,
    f"{names.frozencity_01} - {names.char_fish}" : 11005,
    f"{names.frozencity_02} - {names.char_fish}" : 12005,
    f"{names.frozencity_03} - {names.char_fish}" : 13005,
    f"{names.labs} - {names.char_fish}" :          11006,
    f"{names.palace_01} - {names.char_fish}" :     11007,
    f"{names.palace_02} - {names.char_fish}" :     12007,
    f"{names.palace_03} - {names.char_fish}" :     13007,
    f"{names.campfire} - {names.char_fish}" :      11000,
    f"{names.vault} - {names.char_fish}" :         11100,
    f"{names.oasis} - {names.char_fish}" :         11101,
    f"{names.pizzasewers} - {names.char_fish}" :   11102,
    f"{names.mansion} - {names.char_fish}" :       11103,
    f"{names.cursedcaves} - {names.char_fish}" :   11104,
    f"{names.jungle} - {names.char_fish}" :        11105,
    f"{names.hq_01} - {names.char_fish}" :         11106,
    f"{names.hq_02} - {names.char_fish}" :         12106,
    f"{names.hq_03} - {names.char_fish}" :         13106
}

crystal_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_crystal}" :     21001,
    f"{names.desert_02} - {names.char_crystal}" :     22001,
    f"{names.desert_03} - {names.char_crystal}" :     23001,
    f"{names.sewers} - {names.char_crystal}" :        21002,
    f"{names.scrapyard_01} - {names.char_crystal}" :  21003,
    f"{names.scrapyard_02} - {names.char_crystal}" :  22003,
    f"{names.scrapyard_03} - {names.char_crystal}" :  23003,
    f"{names.caves} - {names.char_crystal}" :         21004,
    f"{names.frozencity_01} - {names.char_crystal}" : 21005,
    f"{names.frozencity_02} - {names.char_crystal}" : 22005,
    f"{names.frozencity_03} - {names.char_crystal}" : 23005,
    f"{names.labs} - {names.char_crystal}" :          21006,
    f"{names.palace_01} - {names.char_crystal}" :     21007,
    f"{names.palace_02} - {names.char_crystal}" :     22007,
    f"{names.palace_03} - {names.char_crystal}" :     23007,
    f"{names.campfire} - {names.char_crystal}" :      21000,
    f"{names.vault} - {names.char_crystal}" :         21100,
    f"{names.oasis} - {names.char_crystal}" :         21101,
    f"{names.pizzasewers} - {names.char_crystal}" :   21102,
    f"{names.mansion} - {names.char_crystal}" :       21103,
    f"{names.cursedcaves} - {names.char_crystal}" :   21104,
    f"{names.jungle} - {names.char_crystal}" :        21105,
    f"{names.hq_01} - {names.char_crystal}" :         21106,
    f"{names.hq_02} - {names.char_crystal}" :         22106,
    f"{names.hq_03} - {names.char_crystal}" :         23106
}

eyes_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_eyes}" :     31001,
    f"{names.desert_02} - {names.char_eyes}" :     32001,
    f"{names.desert_03} - {names.char_eyes}" :     33001,
    f"{names.sewers} - {names.char_eyes}" :        31002,
    f"{names.scrapyard_01} - {names.char_eyes}" :  31003,
    f"{names.scrapyard_02} - {names.char_eyes}" :  32003,
    f"{names.scrapyard_03} - {names.char_eyes}" :  33003,
    f"{names.caves} - {names.char_eyes}" :         31004,
    f"{names.frozencity_01} - {names.char_eyes}" : 31005,
    f"{names.frozencity_02} - {names.char_eyes}" : 32005,
    f"{names.frozencity_03} - {names.char_eyes}" : 33005,
    f"{names.labs} - {names.char_eyes}" :          31006,
    f"{names.palace_01} - {names.char_eyes}" :     31007,
    f"{names.palace_02} - {names.char_eyes}" :     32007,
    f"{names.palace_03} - {names.char_eyes}" :     33007,
    f"{names.campfire} - {names.char_eyes}" :      31000,
    f"{names.vault} - {names.char_eyes}" :         31100,
    f"{names.oasis} - {names.char_eyes}" :         31101,
    f"{names.pizzasewers} - {names.char_eyes}" :   31102,
    f"{names.mansion} - {names.char_eyes}" :       31103,
    f"{names.cursedcaves} - {names.char_eyes}" :   31104,
    f"{names.jungle} - {names.char_eyes}" :        31105,
    f"{names.hq_01} - {names.char_eyes}" :         31106,
    f"{names.hq_02} - {names.char_eyes}" :         32106,
    f"{names.hq_03} - {names.char_eyes}" :         33106
}

melting_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_melting}" :     41001,
    f"{names.desert_02} - {names.char_melting}" :     42001,
    f"{names.desert_03} - {names.char_melting}" :     43001,
    f"{names.sewers} - {names.char_melting}" :        41002,
    f"{names.scrapyard_01} - {names.char_melting}" :  41003,
    f"{names.scrapyard_02} - {names.char_melting}" :  42003,
    f"{names.scrapyard_03} - {names.char_melting}" :  43003,
    f"{names.caves} - {names.char_melting}" :         41004,
    f"{names.frozencity_01} - {names.char_melting}" : 41005,
    f"{names.frozencity_02} - {names.char_melting}" : 42005,
    f"{names.frozencity_03} - {names.char_melting}" : 43005,
    f"{names.labs} - {names.char_melting}" :          41006,
    f"{names.palace_01} - {names.char_melting}" :     41007,
    f"{names.palace_02} - {names.char_melting}" :     42007,
    f"{names.palace_03} - {names.char_melting}" :     43007,
    f"{names.campfire} - {names.char_melting}" :      41000,
    f"{names.vault} - {names.char_melting}" :         41100,
    f"{names.oasis} - {names.char_melting}" :         41101,
    f"{names.pizzasewers} - {names.char_melting}" :   41102,
    f"{names.mansion} - {names.char_melting}" :       41103,
    f"{names.cursedcaves} - {names.char_melting}" :   41104,
    f"{names.jungle} - {names.char_melting}" :        41105,
    f"{names.hq_01} - {names.char_melting}" :         41106,
    f"{names.hq_02} - {names.char_melting}" :         42106,
    f"{names.hq_03} - {names.char_melting}" :         43106
}

plant_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_plant}" :     51001,
    f"{names.desert_02} - {names.char_plant}" :     52001,
    f"{names.desert_03} - {names.char_plant}" :     53001,
    f"{names.sewers} - {names.char_plant}" :        51002,
    f"{names.scrapyard_01} - {names.char_plant}" :  51003,
    f"{names.scrapyard_02} - {names.char_plant}" :  52003,
    f"{names.scrapyard_03} - {names.char_plant}" :  53003,
    f"{names.caves} - {names.char_plant}" :         51004,
    f"{names.frozencity_01} - {names.char_plant}" : 51005,
    f"{names.frozencity_02} - {names.char_plant}" : 52005,
    f"{names.frozencity_03} - {names.char_plant}" : 53005,
    f"{names.labs} - {names.char_plant}" :          51006,
    f"{names.palace_01} - {names.char_plant}" :     51007,
    f"{names.palace_02} - {names.char_plant}" :     52007,
    f"{names.palace_03} - {names.char_plant}" :     53007,
    f"{names.campfire} - {names.char_plant}" :      51000,
    f"{names.vault} - {names.char_plant}" :         51100,
    f"{names.oasis} - {names.char_plant}" :         51101,
    f"{names.pizzasewers} - {names.char_plant}" :   51102,
    f"{names.mansion} - {names.char_plant}" :       51103,
    f"{names.cursedcaves} - {names.char_plant}" :   51104,
    f"{names.jungle} - {names.char_plant}" :        51105,
    f"{names.hq_01} - {names.char_plant}" :         51106,
    f"{names.hq_02} - {names.char_plant}" :         52106,
    f"{names.hq_03} - {names.char_plant}" :         53106
}

yv_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_yv}" :     61001,
    f"{names.desert_02} - {names.char_yv}" :     62001,
    f"{names.desert_03} - {names.char_yv}" :     63001,
    f"{names.sewers} - {names.char_yv}" :        61002,
    f"{names.scrapyard_01} - {names.char_yv}" :  61003,
    f"{names.scrapyard_02} - {names.char_yv}" :  62003,
    f"{names.scrapyard_03} - {names.char_yv}" :  63003,
    f"{names.caves} - {names.char_yv}" :         61004,
    f"{names.frozencity_01} - {names.char_yv}" : 61005,
    f"{names.frozencity_02} - {names.char_yv}" : 62005,
    f"{names.frozencity_03} - {names.char_yv}" : 63005,
    f"{names.labs} - {names.char_yv}" :          61006,
    f"{names.palace_01} - {names.char_yv}" :     61007,
    f"{names.palace_02} - {names.char_yv}" :     62007,
    f"{names.palace_03} - {names.char_yv}" :     63007,
    f"{names.campfire} - {names.char_yv}" :      61000,
    f"{names.vault} - {names.char_yv}" :         61100,
    f"{names.oasis} - {names.char_yv}" :         61101,
    f"{names.pizzasewers} - {names.char_yv}" :   61102,
    f"{names.mansion} - {names.char_yv}" :       61103,
    f"{names.cursedcaves} - {names.char_yv}" :   61104,
    f"{names.jungle} - {names.char_yv}" :        61105,
    f"{names.hq_01} - {names.char_yv}" :         61106,
    f"{names.hq_02} - {names.char_yv}" :         62106,
    f"{names.hq_03} - {names.char_yv}" :         63106
}

steroids_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_steroids}" :     71001,
    f"{names.desert_02} - {names.char_steroids}" :     72001,
    f"{names.desert_03} - {names.char_steroids}" :     73001,
    f"{names.sewers} - {names.char_steroids}" :        71002,
    f"{names.scrapyard_01} - {names.char_steroids}" :  71003,
    f"{names.scrapyard_02} - {names.char_steroids}" :  72003,
    f"{names.scrapyard_03} - {names.char_steroids}" :  73003,
    f"{names.caves} - {names.char_steroids}" :         71004,
    f"{names.frozencity_01} - {names.char_steroids}" : 71005,
    f"{names.frozencity_02} - {names.char_steroids}" : 72005,
    f"{names.frozencity_03} - {names.char_steroids}" : 73005,
    f"{names.labs} - {names.char_steroids}" :          71006,
    f"{names.palace_01} - {names.char_steroids}" :     71007,
    f"{names.palace_02} - {names.char_steroids}" :     72007,
    f"{names.palace_03} - {names.char_steroids}" :     73007,
    f"{names.campfire} - {names.char_steroids}" :      71000,
    f"{names.vault} - {names.char_steroids}" :         71100,
    f"{names.oasis} - {names.char_steroids}" :         71101,
    f"{names.pizzasewers} - {names.char_steroids}" :   71102,
    f"{names.mansion} - {names.char_steroids}" :       71103,
    f"{names.cursedcaves} - {names.char_steroids}" :   71104,
    f"{names.jungle} - {names.char_steroids}" :        71105,
    f"{names.hq_01} - {names.char_steroids}" :         71106,
    f"{names.hq_02} - {names.char_steroids}" :         72106,
    f"{names.hq_03} - {names.char_steroids}" :         73106
}

robot_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_robot}" :     81001,
    f"{names.desert_02} - {names.char_robot}" :     82001,
    f"{names.desert_03} - {names.char_robot}" :     83001,
    f"{names.sewers} - {names.char_robot}" :        81002,
    f"{names.scrapyard_01} - {names.char_robot}" :  81003,
    f"{names.scrapyard_02} - {names.char_robot}" :  82003,
    f"{names.scrapyard_03} - {names.char_robot}" :  83003,
    f"{names.caves} - {names.char_robot}" :         81004,
    f"{names.frozencity_01} - {names.char_robot}" : 81005,
    f"{names.frozencity_02} - {names.char_robot}" : 82005,
    f"{names.frozencity_03} - {names.char_robot}" : 83005,
    f"{names.labs} - {names.char_robot}" :          81006,
    f"{names.palace_01} - {names.char_robot}" :     81007,
    f"{names.palace_02} - {names.char_robot}" :     82007,
    f"{names.palace_03} - {names.char_robot}" :     83007,
    f"{names.campfire} - {names.char_robot}" :      81000,
    f"{names.vault} - {names.char_robot}" :         81100,
    f"{names.oasis} - {names.char_robot}" :         81101,
    f"{names.pizzasewers} - {names.char_robot}" :   81102,
    f"{names.mansion} - {names.char_robot}" :       81103,
    f"{names.cursedcaves} - {names.char_robot}" :   81104,
    f"{names.jungle} - {names.char_robot}" :        81105,
    f"{names.hq_01} - {names.char_robot}" :         81106,
    f"{names.hq_02} - {names.char_robot}" :         82106,
    f"{names.hq_03} - {names.char_robot}" :         83106
}

chicken_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_chicken}" :     91001,
    f"{names.desert_02} - {names.char_chicken}" :     92001,
    f"{names.desert_03} - {names.char_chicken}" :     93001,
    f"{names.sewers} - {names.char_chicken}" :        91002,
    f"{names.scrapyard_01} - {names.char_chicken}" :  91003,
    f"{names.scrapyard_02} - {names.char_chicken}" :  92003,
    f"{names.scrapyard_03} - {names.char_chicken}" :  93003,
    f"{names.caves} - {names.char_chicken}" :         91004,
    f"{names.frozencity_01} - {names.char_chicken}" : 91005,
    f"{names.frozencity_02} - {names.char_chicken}" : 92005,
    f"{names.frozencity_03} - {names.char_chicken}" : 93005,
    f"{names.labs} - {names.char_chicken}" :          91006,
    f"{names.palace_01} - {names.char_chicken}" :     91007,
    f"{names.palace_02} - {names.char_chicken}" :     92007,
    f"{names.palace_03} - {names.char_chicken}" :     93007,
    f"{names.campfire} - {names.char_chicken}" :      91000,
    f"{names.vault} - {names.char_chicken}" :         91100,
    f"{names.oasis} - {names.char_chicken}" :         91101,
    f"{names.pizzasewers} - {names.char_chicken}" :   91102,
    f"{names.mansion} - {names.char_chicken}" :       91103,
    f"{names.cursedcaves} - {names.char_chicken}" :   91104,
    f"{names.jungle} - {names.char_chicken}" :        91105,
    f"{names.hq_01} - {names.char_chicken}" :         91106,
    f"{names.hq_02} - {names.char_chicken}" :         92106,
    f"{names.hq_03} - {names.char_chicken}" :         93106
}

rebel_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_rebel}" :     101001,
    f"{names.desert_02} - {names.char_rebel}" :     102001,
    f"{names.desert_03} - {names.char_rebel}" :     103001,
    f"{names.sewers} - {names.char_rebel}" :        101002,
    f"{names.scrapyard_01} - {names.char_rebel}" :  101003,
    f"{names.scrapyard_02} - {names.char_rebel}" :  102003,
    f"{names.scrapyard_03} - {names.char_rebel}" :  103003,
    f"{names.caves} - {names.char_rebel}" :         101004,
    f"{names.frozencity_01} - {names.char_rebel}" : 101005,
    f"{names.frozencity_02} - {names.char_rebel}" : 102005,
    f"{names.frozencity_03} - {names.char_rebel}" : 103005,
    f"{names.labs} - {names.char_rebel}" :          101006,
    f"{names.palace_01} - {names.char_rebel}" :     101007,
    f"{names.palace_02} - {names.char_rebel}" :     102007,
    f"{names.palace_03} - {names.char_rebel}" :     103007,
    f"{names.campfire} - {names.char_rebel}" :      101000,
    f"{names.vault} - {names.char_rebel}" :         101100,
    f"{names.oasis} - {names.char_rebel}" :         101101,
    f"{names.pizzasewers} - {names.char_rebel}" :   101102,
    f"{names.mansion} - {names.char_rebel}" :       101103,
    f"{names.cursedcaves} - {names.char_rebel}" :   101104,
    f"{names.jungle} - {names.char_rebel}" :        101105,
    f"{names.hq_01} - {names.char_rebel}" :         101106,
    f"{names.hq_02} - {names.char_rebel}" :         102106,
    f"{names.hq_03} - {names.char_rebel}" :         103106
}

horror_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_horror}" :     111001,
    f"{names.desert_02} - {names.char_horror}" :     112001,
    f"{names.desert_03} - {names.char_horror}" :     113001,
    f"{names.sewers} - {names.char_horror}" :        111002,
    f"{names.scrapyard_01} - {names.char_horror}" :  111003,
    f"{names.scrapyard_02} - {names.char_horror}" :  112003,
    f"{names.scrapyard_03} - {names.char_horror}" :  113003,
    f"{names.caves} - {names.char_horror}" :         111004,
    f"{names.frozencity_01} - {names.char_horror}" : 111005,
    f"{names.frozencity_02} - {names.char_horror}" : 112005,
    f"{names.frozencity_03} - {names.char_horror}" : 113005,
    f"{names.labs} - {names.char_horror}" :          111006,
    f"{names.palace_01} - {names.char_horror}" :     111007,
    f"{names.palace_02} - {names.char_horror}" :     112007,
    f"{names.palace_03} - {names.char_horror}" :     113007,
    f"{names.campfire} - {names.char_horror}" :      111000,
    f"{names.vault} - {names.char_horror}" :         111100,
    f"{names.oasis} - {names.char_horror}" :         111101,
    f"{names.pizzasewers} - {names.char_horror}" :   111102,
    f"{names.mansion} - {names.char_horror}" :       111103,
    f"{names.cursedcaves} - {names.char_horror}" :   111104,
    f"{names.jungle} - {names.char_horror}" :        111105,
    f"{names.hq_01} - {names.char_horror}" :         111106,
    f"{names.hq_02} - {names.char_horror}" :         112106,
    f"{names.hq_03} - {names.char_horror}" :         113106
}

rogue_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_rogue}" :     121001,
    f"{names.desert_02} - {names.char_rogue}" :     122001,
    f"{names.desert_03} - {names.char_rogue}" :     123001,
    f"{names.sewers} - {names.char_rogue}" :        121002,
    f"{names.scrapyard_01} - {names.char_rogue}" :  121003,
    f"{names.scrapyard_02} - {names.char_rogue}" :  122003,
    f"{names.scrapyard_03} - {names.char_rogue}" :  123003,
    f"{names.caves} - {names.char_rogue}" :         121004,
    f"{names.frozencity_01} - {names.char_rogue}" : 121005,
    f"{names.frozencity_02} - {names.char_rogue}" : 122005,
    f"{names.frozencity_03} - {names.char_rogue}" : 123005,
    f"{names.labs} - {names.char_rogue}" :          121006,
    f"{names.palace_01} - {names.char_rogue}" :     121007,
    f"{names.palace_02} - {names.char_rogue}" :     122007,
    f"{names.palace_03} - {names.char_rogue}" :     123007,
    f"{names.campfire} - {names.char_rogue}" :      121000,
    f"{names.vault} - {names.char_rogue}" :         121100,
    f"{names.oasis} - {names.char_rogue}" :         121101,
    f"{names.pizzasewers} - {names.char_rogue}" :   121102,
    f"{names.mansion} - {names.char_rogue}" :       121103,
    f"{names.cursedcaves} - {names.char_rogue}" :   121104,
    f"{names.jungle} - {names.char_rogue}" :        121105,
    f"{names.hq_01} - {names.char_rogue}" :         121106,
    f"{names.hq_02} - {names.char_rogue}" :         122106,
    f"{names.hq_03} - {names.char_rogue}" :         123106
}

cuz_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_cuz}" :     161001,
    f"{names.desert_02} - {names.char_cuz}" :     162001,
    f"{names.desert_03} - {names.char_cuz}" :     163001,
    f"{names.sewers} - {names.char_cuz}" :        161002,
    f"{names.scrapyard_01} - {names.char_cuz}" :  161003,
    f"{names.scrapyard_02} - {names.char_cuz}" :  162003,
    f"{names.scrapyard_03} - {names.char_cuz}" :  163003,
    f"{names.caves} - {names.char_cuz}" :         161004,
    f"{names.frozencity_01} - {names.char_cuz}" : 161005,
    f"{names.frozencity_02} - {names.char_cuz}" : 162005,
    f"{names.frozencity_03} - {names.char_cuz}" : 163005,
    f"{names.labs} - {names.char_cuz}" :          161006,
    f"{names.palace_01} - {names.char_cuz}" :     161007,
    f"{names.palace_02} - {names.char_cuz}" :     162007,
    f"{names.palace_03} - {names.char_cuz}" :     163007,
    f"{names.campfire} - {names.char_cuz}" :      161000,
    f"{names.vault} - {names.char_cuz}" :         161100,
    f"{names.oasis} - {names.char_cuz}" :         161101,
    f"{names.pizzasewers} - {names.char_cuz}" :   161102,
    f"{names.mansion} - {names.char_cuz}" :       161103,
    f"{names.cursedcaves} - {names.char_cuz}" :   161104,
    f"{names.jungle} - {names.char_cuz}" :        161105,
    f"{names.hq_01} - {names.char_cuz}" :         161106,
    f"{names.hq_02} - {names.char_cuz}" :         162106,
    f"{names.hq_03} - {names.char_cuz}" :         163106
}

desert_01_locations: Dict[str, int] = {
    f"{names.desert_01} - {names.char_fish}" :      11001,
    f"{names.desert_01} - {names.char_crystal}" :   21001,
    f"{names.desert_01} - {names.char_eyes}" :      31001,
    f"{names.desert_01} - {names.char_melting}" :   41001,
    f"{names.desert_01} - {names.char_plant}" :     51001,
    f"{names.desert_01} - {names.char_yv}" :        61001,
    f"{names.desert_01} - {names.char_steroids}" :  71001,
    f"{names.desert_01} - {names.char_robot}" :     81001,
    f"{names.desert_01} - {names.char_chicken}" :   91001,
    f"{names.desert_01} - {names.char_rebel}" :    101001,
    f"{names.desert_01} - {names.char_horror}" :   111001,
    f"{names.desert_01} - {names.char_rogue}" :    121001,
    f"{names.desert_01} - {names.char_cuz}" :      161001,
}

desert_02_locations: Dict[str, int] = {
    f"{names.desert_02} - {names.char_fish}" :      12001,
    f"{names.desert_02} - {names.char_crystal}" :   22001,
    f"{names.desert_02} - {names.char_eyes}" :      32001,
    f"{names.desert_02} - {names.char_melting}" :   42001,
    f"{names.desert_02} - {names.char_plant}" :     52001,
    f"{names.desert_02} - {names.char_yv}" :        62001,
    f"{names.desert_02} - {names.char_steroids}" :  72001,
    f"{names.desert_02} - {names.char_robot}" :     82001,
    f"{names.desert_02} - {names.char_chicken}" :   92001,
    f"{names.desert_02} - {names.char_rebel}" :    102001,
    f"{names.desert_02} - {names.char_horror}" :   112001,
    f"{names.desert_02} - {names.char_rogue}" :    122001,
    f"{names.desert_02} - {names.char_cuz}" :      162001,
}

desert_03_locations: Dict[str, int] = {
    f"{names.desert_03} - {names.char_fish}" :      13001,
    f"{names.desert_03} - {names.char_crystal}" :   23001,
    f"{names.desert_03} - {names.char_eyes}" :      33001,
    f"{names.desert_03} - {names.char_melting}" :   43001,
    f"{names.desert_03} - {names.char_plant}" :     53001,
    f"{names.desert_03} - {names.char_yv}" :        63001,
    f"{names.desert_03} - {names.char_steroids}" :  73001,
    f"{names.desert_03} - {names.char_robot}" :     83001,
    f"{names.desert_03} - {names.char_chicken}" :   93001,
    f"{names.desert_03} - {names.char_rebel}" :    103001,
    f"{names.desert_03} - {names.char_horror}" :   113001,
    f"{names.desert_03} - {names.char_rogue}" :    123001,
    f"{names.desert_03} - {names.char_cuz}" :      163001,
}

sewers_locations: Dict[str, int] = {
    f"{names.sewers} - {names.char_fish}" :      11002,
    f"{names.sewers} - {names.char_crystal}" :   21002,
    f"{names.sewers} - {names.char_eyes}" :      31002,
    f"{names.sewers} - {names.char_melting}" :   41002,
    f"{names.sewers} - {names.char_plant}" :     51002,
    f"{names.sewers} - {names.char_yv}" :        61002,
    f"{names.sewers} - {names.char_steroids}" :  71002,
    f"{names.sewers} - {names.char_robot}" :     81002,
    f"{names.sewers} - {names.char_chicken}" :   91002,
    f"{names.sewers} - {names.char_rebel}" :    101002,
    f"{names.sewers} - {names.char_horror}" :   111002,
    f"{names.sewers} - {names.char_rogue}" :    121002,
    f"{names.sewers} - {names.char_cuz}" :      161002,
}

scrapyard_01_locations: Dict[str, int] = {
    f"{names.scrapyard_01} - {names.char_fish}" :      11003,
    f"{names.scrapyard_01} - {names.char_crystal}" :   21003,
    f"{names.scrapyard_01} - {names.char_eyes}" :      31003,
    f"{names.scrapyard_01} - {names.char_melting}" :   41003,
    f"{names.scrapyard_01} - {names.char_plant}" :     51003,
    f"{names.scrapyard_01} - {names.char_yv}" :        61003,
    f"{names.scrapyard_01} - {names.char_steroids}" :  71003,
    f"{names.scrapyard_01} - {names.char_robot}" :     81003,
    f"{names.scrapyard_01} - {names.char_chicken}" :   91003,
    f"{names.scrapyard_01} - {names.char_rebel}" :    101003,
    f"{names.scrapyard_01} - {names.char_horror}" :   111003,
    f"{names.scrapyard_01} - {names.char_rogue}" :    121003,
    f"{names.scrapyard_01} - {names.char_cuz}" :      161003,
}

scrapyard_02_locations: Dict[str, int] = {
    f"{names.scrapyard_02} - {names.char_fish}" :      12003,
    f"{names.scrapyard_02} - {names.char_crystal}" :   22003,
    f"{names.scrapyard_02} - {names.char_eyes}" :      32003,
    f"{names.scrapyard_02} - {names.char_melting}" :   42003,
    f"{names.scrapyard_02} - {names.char_plant}" :     52003,
    f"{names.scrapyard_02} - {names.char_yv}" :        62003,
    f"{names.scrapyard_02} - {names.char_steroids}" :  72003,
    f"{names.scrapyard_02} - {names.char_robot}" :     82003,
    f"{names.scrapyard_02} - {names.char_chicken}" :   92003,
    f"{names.scrapyard_02} - {names.char_rebel}" :    102003,
    f"{names.scrapyard_02} - {names.char_horror}" :   112003,
    f"{names.scrapyard_02} - {names.char_rogue}" :    122003,
    f"{names.scrapyard_02} - {names.char_cuz}" :      162003,
}

scrapyard_03_locations: Dict[str, int] = {
    f"{names.scrapyard_03} - {names.char_fish}" :      13003,
    f"{names.scrapyard_03} - {names.char_crystal}" :   23003,
    f"{names.scrapyard_03} - {names.char_eyes}" :      33003,
    f"{names.scrapyard_03} - {names.char_melting}" :   43003,
    f"{names.scrapyard_03} - {names.char_plant}" :     53003,
    f"{names.scrapyard_03} - {names.char_yv}" :        63003,
    f"{names.scrapyard_03} - {names.char_steroids}" :  73003,
    f"{names.scrapyard_03} - {names.char_robot}" :     83003,
    f"{names.scrapyard_03} - {names.char_chicken}" :   93003,
    f"{names.scrapyard_03} - {names.char_rebel}" :    103003,
    f"{names.scrapyard_03} - {names.char_horror}" :   113003,
    f"{names.scrapyard_03} - {names.char_rogue}" :    123003,
    f"{names.scrapyard_03} - {names.char_cuz}" :      163003,
}

caves_locations: Dict[str, int] = {
    f"{names.caves} - {names.char_fish}" :      11004,
    f"{names.caves} - {names.char_crystal}" :   21004,
    f"{names.caves} - {names.char_eyes}" :      31004,
    f"{names.caves} - {names.char_melting}" :   41004,
    f"{names.caves} - {names.char_plant}" :     51004,
    f"{names.caves} - {names.char_yv}" :        61004,
    f"{names.caves} - {names.char_steroids}" :  71004,
    f"{names.caves} - {names.char_robot}" :     81004,
    f"{names.caves} - {names.char_chicken}" :   91004,
    f"{names.caves} - {names.char_rebel}" :    101004,
    f"{names.caves} - {names.char_horror}" :   111004,
    f"{names.caves} - {names.char_rogue}" :    121004,
    f"{names.caves} - {names.char_cuz}" :      161004,
}

frozencity_01_locations: Dict[str, int] = {
    f"{names.frozencity_01} - {names.char_fish}" :      11005,
    f"{names.frozencity_01} - {names.char_crystal}" :   21005,
    f"{names.frozencity_01} - {names.char_eyes}" :      31005,
    f"{names.frozencity_01} - {names.char_melting}" :   41005,
    f"{names.frozencity_01} - {names.char_plant}" :     51005,
    f"{names.frozencity_01} - {names.char_yv}" :        61005,
    f"{names.frozencity_01} - {names.char_steroids}" :  71005,
    f"{names.frozencity_01} - {names.char_robot}" :     81005,
    f"{names.frozencity_01} - {names.char_chicken}" :   91005,
    f"{names.frozencity_01} - {names.char_rebel}" :    101005,
    f"{names.frozencity_01} - {names.char_horror}" :   111005,
    f"{names.frozencity_01} - {names.char_rogue}" :    121005,
    f"{names.frozencity_01} - {names.char_cuz}" :      161005,
}

frozencity_02_locations: Dict[str, int] = {
    f"{names.frozencity_02} - {names.char_fish}" :      12005,
    f"{names.frozencity_02} - {names.char_crystal}" :   22005,
    f"{names.frozencity_02} - {names.char_eyes}" :      32005,
    f"{names.frozencity_02} - {names.char_melting}" :   42005,
    f"{names.frozencity_02} - {names.char_plant}" :     52005,
    f"{names.frozencity_02} - {names.char_yv}" :        62005,
    f"{names.frozencity_02} - {names.char_steroids}" :  72005,
    f"{names.frozencity_02} - {names.char_robot}" :     82005,
    f"{names.frozencity_02} - {names.char_chicken}" :   92005,
    f"{names.frozencity_02} - {names.char_rebel}" :    102005,
    f"{names.frozencity_02} - {names.char_horror}" :   112005,
    f"{names.frozencity_02} - {names.char_rogue}" :    122005,
    f"{names.frozencity_02} - {names.char_cuz}" :      162005,
}

frozencity_03_locations: Dict[str, int] = {
    f"{names.frozencity_03} - {names.char_fish}" :      13005,
    f"{names.frozencity_03} - {names.char_crystal}" :   23005,
    f"{names.frozencity_03} - {names.char_eyes}" :      33005,
    f"{names.frozencity_03} - {names.char_melting}" :   43005,
    f"{names.frozencity_03} - {names.char_plant}" :     53005,
    f"{names.frozencity_03} - {names.char_yv}" :        63005,
    f"{names.frozencity_03} - {names.char_steroids}" :  73005,
    f"{names.frozencity_03} - {names.char_robot}" :     83005,
    f"{names.frozencity_03} - {names.char_chicken}" :   93005,
    f"{names.frozencity_03} - {names.char_rebel}" :    103005,
    f"{names.frozencity_03} - {names.char_horror}" :   113005,
    f"{names.frozencity_03} - {names.char_rogue}" :    123005,
    f"{names.frozencity_03} - {names.char_cuz}" :      163005,
}

labs_locations: Dict[str, int] = {
    f"{names.labs} - {names.char_fish}" :      11006,
    f"{names.labs} - {names.char_crystal}" :   21006,
    f"{names.labs} - {names.char_eyes}" :      31006,
    f"{names.labs} - {names.char_melting}" :   41006,
    f"{names.labs} - {names.char_plant}" :     51006,
    f"{names.labs} - {names.char_yv}" :        61006,
    f"{names.labs} - {names.char_steroids}" :  71006,
    f"{names.labs} - {names.char_robot}" :     81006,
    f"{names.labs} - {names.char_chicken}" :   91006,
    f"{names.labs} - {names.char_rebel}" :    101006,
    f"{names.labs} - {names.char_horror}" :   111006,
    f"{names.labs} - {names.char_rogue}" :    121006,
    f"{names.labs} - {names.char_cuz}" :      161006,
}

palace_01_locations: Dict[str, int] = {
    f"{names.palace_01} - {names.char_fish}" :      11007,
    f"{names.palace_01} - {names.char_crystal}" :   21007,
    f"{names.palace_01} - {names.char_eyes}" :      31007,
    f"{names.palace_01} - {names.char_melting}" :   41007,
    f"{names.palace_01} - {names.char_plant}" :     51007,
    f"{names.palace_01} - {names.char_yv}" :        61007,
    f"{names.palace_01} - {names.char_steroids}" :  71007,
    f"{names.palace_01} - {names.char_robot}" :     81007,
    f"{names.palace_01} - {names.char_chicken}" :   91007,
    f"{names.palace_01} - {names.char_rebel}" :    101007,
    f"{names.palace_01} - {names.char_horror}" :   111007,
    f"{names.palace_01} - {names.char_rogue}" :    121007,
    f"{names.palace_01} - {names.char_cuz}" :      161007,
}

palace_02_locations: Dict[str, int] = {
    f"{names.palace_02} - {names.char_fish}" :      12007,
    f"{names.palace_02} - {names.char_crystal}" :   22007,
    f"{names.palace_02} - {names.char_eyes}" :      32007,
    f"{names.palace_02} - {names.char_melting}" :   42007,
    f"{names.palace_02} - {names.char_plant}" :     52007,
    f"{names.palace_02} - {names.char_yv}" :        62007,
    f"{names.palace_02} - {names.char_steroids}" :  72007,
    f"{names.palace_02} - {names.char_robot}" :     82007,
    f"{names.palace_02} - {names.char_chicken}" :   92007,
    f"{names.palace_02} - {names.char_rebel}" :    102007,
    f"{names.palace_02} - {names.char_horror}" :   112007,
    f"{names.palace_02} - {names.char_rogue}" :    122007,
    f"{names.palace_02} - {names.char_cuz}" :      162007,
}

palace_03_locations: Dict[str, int] = {
    f"{names.palace_03} - {names.char_fish}" :      13007,
    f"{names.palace_03} - {names.char_crystal}" :   23007,
    f"{names.palace_03} - {names.char_eyes}" :      33007,
    f"{names.palace_03} - {names.char_melting}" :   43007,
    f"{names.palace_03} - {names.char_plant}" :     53007,
    f"{names.palace_03} - {names.char_yv}" :        63007,
    f"{names.palace_03} - {names.char_steroids}" :  73007,
    f"{names.palace_03} - {names.char_robot}" :     83007,
    f"{names.palace_03} - {names.char_chicken}" :   93007,
    f"{names.palace_03} - {names.char_rebel}" :    103007,
    f"{names.palace_03} - {names.char_horror}" :   113007,
    f"{names.palace_03} - {names.char_rogue}" :    123007,
    f"{names.palace_03} - {names.char_cuz}" :      163007,
}

campfire_locations: Dict[str, int] = {
    f"{names.campfire} - {names.char_fish}" :      11000,
    f"{names.campfire} - {names.char_crystal}" :   21000,
    f"{names.campfire} - {names.char_eyes}" :      31000,
    f"{names.campfire} - {names.char_melting}" :   41000,
    f"{names.campfire} - {names.char_plant}" :     51000,
    f"{names.campfire} - {names.char_yv}" :        61000,
    f"{names.campfire} - {names.char_steroids}" :  71000,
    f"{names.campfire} - {names.char_robot}" :     81000,
    f"{names.campfire} - {names.char_chicken}" :   91000,
    f"{names.campfire} - {names.char_rebel}" :    101000,
    f"{names.campfire} - {names.char_horror}" :   111000,
    f"{names.campfire} - {names.char_rogue}" :    121000,
    f"{names.campfire} - {names.char_cuz}" :      161000,
}

vault_locations: Dict[str, int] = {
    f"{names.vault} - {names.char_fish}" :      11100,
    f"{names.vault} - {names.char_crystal}" :   21100,
    f"{names.vault} - {names.char_eyes}" :      31100,
    f"{names.vault} - {names.char_melting}" :   41100,
    f"{names.vault} - {names.char_plant}" :     51100,
    f"{names.vault} - {names.char_yv}" :        61100,
    f"{names.vault} - {names.char_steroids}" :  71100,
    f"{names.vault} - {names.char_robot}" :     81100,
    f"{names.vault} - {names.char_chicken}" :   91100,
    f"{names.vault} - {names.char_rebel}" :    101100,
    f"{names.vault} - {names.char_horror}" :   111100,
    f"{names.vault} - {names.char_rogue}" :    121100,
    f"{names.vault} - {names.char_cuz}" :      161100,
}

oasis_locations: Dict[str, int] = {
    f"{names.oasis} - {names.char_fish}" :      11101,
    f"{names.oasis} - {names.char_crystal}" :   21101,
    f"{names.oasis} - {names.char_eyes}" :      31101,
    f"{names.oasis} - {names.char_melting}" :   41101,
    f"{names.oasis} - {names.char_plant}" :     51101,
    f"{names.oasis} - {names.char_yv}" :        61101,
    f"{names.oasis} - {names.char_steroids}" :  71101,
    f"{names.oasis} - {names.char_robot}" :     81101,
    f"{names.oasis} - {names.char_chicken}" :   91101,
    f"{names.oasis} - {names.char_rebel}" :    101101,
    f"{names.oasis} - {names.char_horror}" :   111101,
    f"{names.oasis} - {names.char_rogue}" :    121101,
    f"{names.oasis} - {names.char_cuz}" :      161101,
}

pizzasewers_locations: Dict[str, int] = {
    f"{names.pizzasewers} - {names.char_fish}" :      11102,
    f"{names.pizzasewers} - {names.char_crystal}" :   21102,
    f"{names.pizzasewers} - {names.char_eyes}" :      31102,
    f"{names.pizzasewers} - {names.char_melting}" :   41102,
    f"{names.pizzasewers} - {names.char_plant}" :     51102,
    f"{names.pizzasewers} - {names.char_yv}" :        61102,
    f"{names.pizzasewers} - {names.char_steroids}" :  71102,
    f"{names.pizzasewers} - {names.char_robot}" :     81102,
    f"{names.pizzasewers} - {names.char_chicken}" :   91102,
    f"{names.pizzasewers} - {names.char_rebel}" :    101102,
    f"{names.pizzasewers} - {names.char_horror}" :   111102,
    f"{names.pizzasewers} - {names.char_rogue}" :    121102,
    f"{names.pizzasewers} - {names.char_cuz}" :      161102,
}

mansion_locations: Dict[str, int] = {
    f"{names.mansion} - {names.char_fish}" :      11103,
    f"{names.mansion} - {names.char_crystal}" :   21103,
    f"{names.mansion} - {names.char_eyes}" :      31103,
    f"{names.mansion} - {names.char_melting}" :   41103,
    f"{names.mansion} - {names.char_plant}" :     51103,
    f"{names.mansion} - {names.char_yv}" :        61103,
    f"{names.mansion} - {names.char_steroids}" :  71103,
    f"{names.mansion} - {names.char_robot}" :     81103,
    f"{names.mansion} - {names.char_chicken}" :   91103,
    f"{names.mansion} - {names.char_rebel}" :    101103,
    f"{names.mansion} - {names.char_horror}" :   111103,
    f"{names.mansion} - {names.char_rogue}" :    121103,
    f"{names.mansion} - {names.char_cuz}" :      161103,
}

cursedcaves_locations: Dict[str, int] = {
    f"{names.cursedcaves} - {names.char_fish}" :      11104,
    f"{names.cursedcaves} - {names.char_crystal}" :   21104,
    f"{names.cursedcaves} - {names.char_eyes}" :      31104,
    f"{names.cursedcaves} - {names.char_melting}" :   41104,
    f"{names.cursedcaves} - {names.char_plant}" :     51104,
    f"{names.cursedcaves} - {names.char_yv}" :        61104,
    f"{names.cursedcaves} - {names.char_steroids}" :  71104,
    f"{names.cursedcaves} - {names.char_robot}" :     81104,
    f"{names.cursedcaves} - {names.char_chicken}" :   91104,
    f"{names.cursedcaves} - {names.char_rebel}" :    101104,
    f"{names.cursedcaves} - {names.char_horror}" :   111104,
    f"{names.cursedcaves} - {names.char_rogue}" :    121104,
    f"{names.cursedcaves} - {names.char_cuz}" :      161104,
}

jungle_locations: Dict[str, int] = {
    f"{names.jungle} - {names.char_fish}" :      11105,
    f"{names.jungle} - {names.char_crystal}" :   21105,
    f"{names.jungle} - {names.char_eyes}" :      31105,
    f"{names.jungle} - {names.char_melting}" :   41105,
    f"{names.jungle} - {names.char_plant}" :     51105,
    f"{names.jungle} - {names.char_yv}" :        61105,
    f"{names.jungle} - {names.char_steroids}" :  71105,
    f"{names.jungle} - {names.char_robot}" :     81105,
    f"{names.jungle} - {names.char_chicken}" :   91105,
    f"{names.jungle} - {names.char_rebel}" :    101105,
    f"{names.jungle} - {names.char_horror}" :   111105,
    f"{names.jungle} - {names.char_rogue}" :    121105,
    f"{names.jungle} - {names.char_cuz}" :      161105,
}

hq_01_locations: Dict[str, int] = {
    f"{names.hq_01} - {names.char_fish}" :      11106,
    f"{names.hq_01} - {names.char_crystal}" :   21106,
    f"{names.hq_01} - {names.char_eyes}" :      31106,
    f"{names.hq_01} - {names.char_melting}" :   41106,
    f"{names.hq_01} - {names.char_plant}" :     51106,
    f"{names.hq_01} - {names.char_yv}" :        61106,
    f"{names.hq_01} - {names.char_steroids}" :  71106,
    f"{names.hq_01} - {names.char_robot}" :     81106,
    f"{names.hq_01} - {names.char_chicken}" :   91106,
    f"{names.hq_01} - {names.char_rebel}" :    101106,
    f"{names.hq_01} - {names.char_horror}" :   111106,
    f"{names.hq_01} - {names.char_rogue}" :    121106,
    f"{names.hq_01} - {names.char_cuz}" :      161106,
}

hq_02_locations: Dict[str, int] = {
    f"{names.hq_02} - {names.char_fish}" :      12106,
    f"{names.hq_02} - {names.char_crystal}" :   22106,
    f"{names.hq_02} - {names.char_eyes}" :      32106,
    f"{names.hq_02} - {names.char_melting}" :   42106,
    f"{names.hq_02} - {names.char_plant}" :     52106,
    f"{names.hq_02} - {names.char_yv}" :        62106,
    f"{names.hq_02} - {names.char_steroids}" :  72106,
    f"{names.hq_02} - {names.char_robot}" :     82106,
    f"{names.hq_02} - {names.char_chicken}" :   92106,
    f"{names.hq_02} - {names.char_rebel}" :    102106,
    f"{names.hq_02} - {names.char_horror}" :   112106,
    f"{names.hq_02} - {names.char_rogue}" :    122106,
    f"{names.hq_02} - {names.char_cuz}" :      162106,
}

hq_03_locations: Dict[str, int] = {
    f"{names.hq_03} - {names.char_fish}" :      13106,
    f"{names.hq_03} - {names.char_crystal}" :   23106,
    f"{names.hq_03} - {names.char_eyes}" :      33106,
    f"{names.hq_03} - {names.char_melting}" :   43106,
    f"{names.hq_03} - {names.char_plant}" :     53106,
    f"{names.hq_03} - {names.char_yv}" :        63106,
    f"{names.hq_03} - {names.char_steroids}" :  73106,
    f"{names.hq_03} - {names.char_robot}" :     83106,
    f"{names.hq_03} - {names.char_chicken}" :   93106,
    f"{names.hq_03} - {names.char_rebel}" :    103106,
    f"{names.hq_03} - {names.char_horror}" :   113106,
    f"{names.hq_03} - {names.char_rogue}" :    123106,
    f"{names.hq_03} - {names.char_cuz}" :      163106,
}

goal_locations: Dict[str, int] = {
    f"GOAL - {names.char_fish}" :     99901,
    f"GOAL - {names.char_crystal}" :  99902,
    f"GOAL - {names.char_eyes}" :     99903,
    f"GOAL - {names.char_melting}" :  99904,
    f"GOAL - {names.char_plant}" :    99905,
    f"GOAL - {names.char_yv}" :       99906,
    f"GOAL - {names.char_steroids}" : 99907,
    f"GOAL - {names.char_robot}" :    99908,
    f"GOAL - {names.char_chicken}" :  99909,
    f"GOAL - {names.char_rebel}" :    99910,
    f"GOAL - {names.char_horror}" :   99911,
    f"GOAL - {names.char_rogue}" :    99912,
    f"GOAL - {names.char_cuz}" :      99916,
}

crown_locations_fish: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_fish}" :      102,
    f"CROWN OF LIFE - {names.char_fish}" :       103,
    f"CROWN OF HASTE - {names.char_fish}" :      104,
    f"CROWN OF GUNS - {names.char_fish}" :       105,
    f"CROWN OF HATRED - {names.char_fish}" :     106,
    f"CROWN OF BLOOD - {names.char_fish}" :      107,
    f"CROWN OF DESTINY - {names.char_fish}" :    108,
    f"CROWN OF LOVE - {names.char_fish}" :       109,
    f"CROWN OF LUCK - {names.char_fish}" :       110,
    f"CROWN OF CURSES - {names.char_fish}" :     111,
    f"CROWN OF RISK - {names.char_fish}" :       112,
    f"CROWN OF PROTECTION - {names.char_fish}" : 113,
}

crown_locations_crystal: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_crystal}" :      202,
    f"CROWN OF LIFE - {names.char_crystal}" :       203,
    f"CROWN OF HASTE - {names.char_crystal}" :      204,
    f"CROWN OF GUNS - {names.char_crystal}" :       205,
    f"CROWN OF HATRED - {names.char_crystal}" :     206,
    f"CROWN OF BLOOD - {names.char_crystal}" :      207,
    f"CROWN OF DESTINY - {names.char_crystal}" :    208,
    f"CROWN OF LOVE - {names.char_crystal}" :       209,
    f"CROWN OF LUCK - {names.char_crystal}" :       210,
    f"CROWN OF CURSES - {names.char_crystal}" :     211,
    f"CROWN OF RISK - {names.char_crystal}" :       212,
    f"CROWN OF PROTECTION - {names.char_crystal}" : 213,
}

crown_locations_eyes: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_eyes}" :      302,
    f"CROWN OF LIFE - {names.char_eyes}" :       303,
    f"CROWN OF HASTE - {names.char_eyes}" :      304,
    f"CROWN OF GUNS - {names.char_eyes}" :       305,
    f"CROWN OF HATRED - {names.char_eyes}" :     306,
    f"CROWN OF BLOOD - {names.char_eyes}" :      307,
    f"CROWN OF DESTINY - {names.char_eyes}" :    308,
    f"CROWN OF LOVE - {names.char_eyes}" :       309,
    f"CROWN OF LUCK - {names.char_eyes}" :       310,
    f"CROWN OF CURSES - {names.char_eyes}" :     311,
    f"CROWN OF RISK - {names.char_eyes}" :       312,
    f"CROWN OF PROTECTION - {names.char_eyes}" : 313,
}

crown_locations_melting: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_melting}" :      402,
    f"CROWN OF LIFE - {names.char_melting}" :       403,
    f"CROWN OF HASTE - {names.char_melting}" :      404,
    f"CROWN OF GUNS - {names.char_melting}" :       405,
    f"CROWN OF HATRED - {names.char_melting}" :     406,
    f"CROWN OF BLOOD - {names.char_melting}" :      407,
    f"CROWN OF DESTINY - {names.char_melting}" :    408,
    f"CROWN OF LOVE - {names.char_melting}" :       409,
    f"CROWN OF LUCK - {names.char_melting}" :       410,
    f"CROWN OF CURSES - {names.char_melting}" :     411,
    f"CROWN OF RISK - {names.char_melting}" :       412,
    f"CROWN OF PROTECTION - {names.char_melting}" : 413,
}

crown_locations_plant: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_plant}" :      502,
    f"CROWN OF LIFE - {names.char_plant}" :       503,
    f"CROWN OF HASTE - {names.char_plant}" :      504,
    f"CROWN OF GUNS - {names.char_plant}" :       505,
    f"CROWN OF HATRED - {names.char_plant}" :     506,
    f"CROWN OF BLOOD - {names.char_plant}" :      507,
    f"CROWN OF DESTINY - {names.char_plant}" :    508,
    f"CROWN OF LOVE - {names.char_plant}" :       509,
    f"CROWN OF LUCK - {names.char_plant}" :       510,
    f"CROWN OF CURSES - {names.char_plant}" :     511,
    f"CROWN OF RISK - {names.char_plant}" :       512,
    f"CROWN OF PROTECTION - {names.char_plant}" : 513,
}

crown_locations_yv: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_yv}" :      602,
    f"CROWN OF LIFE - {names.char_yv}" :       603,
    f"CROWN OF HASTE - {names.char_yv}" :      604,
    f"CROWN OF GUNS - {names.char_yv}" :       605,
    f"CROWN OF HATRED - {names.char_yv}" :     606,
    f"CROWN OF BLOOD - {names.char_yv}" :      607,
    f"CROWN OF DESTINY - {names.char_yv}" :    608,
    f"CROWN OF LOVE - {names.char_yv}" :       609,
    f"CROWN OF LUCK - {names.char_yv}" :       610,
    f"CROWN OF CURSES - {names.char_yv}" :     611,
    f"CROWN OF RISK - {names.char_yv}" :       612,
    f"CROWN OF PROTECTION - {names.char_yv}" : 613,
}

crown_locations_steroids: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_steroids}" :      702,
    f"CROWN OF LIFE - {names.char_steroids}" :       703,
    f"CROWN OF HASTE - {names.char_steroids}" :      704,
    f"CROWN OF GUNS - {names.char_steroids}" :       705,
    f"CROWN OF HATRED - {names.char_steroids}" :     706,
    f"CROWN OF BLOOD - {names.char_steroids}" :      707,
    f"CROWN OF DESTINY - {names.char_steroids}" :    708,
    f"CROWN OF LOVE - {names.char_steroids}" :       709,
    f"CROWN OF LUCK - {names.char_steroids}" :       710,
    f"CROWN OF CURSES - {names.char_steroids}" :     711,
    f"CROWN OF RISK - {names.char_steroids}" :       712,
    f"CROWN OF PROTECTION - {names.char_steroids}" : 713,
}

crown_locations_robot: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_robot}" :      802,
    f"CROWN OF LIFE - {names.char_robot}" :       803,
    f"CROWN OF HASTE - {names.char_robot}" :      804,
    f"CROWN OF GUNS - {names.char_robot}" :       805,
    f"CROWN OF HATRED - {names.char_robot}" :     806,
    f"CROWN OF BLOOD - {names.char_robot}" :      807,
    f"CROWN OF DESTINY - {names.char_robot}" :    808,
    f"CROWN OF LOVE - {names.char_robot}" :       809,
    f"CROWN OF LUCK - {names.char_robot}" :       810,
    f"CROWN OF CURSES - {names.char_robot}" :     811,
    f"CROWN OF RISK - {names.char_robot}" :       812,
    f"CROWN OF PROTECTION - {names.char_robot}" : 813,
}

crown_locations_chicken: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_chicken}" :      902,
    f"CROWN OF LIFE - {names.char_chicken}" :       903,
    f"CROWN OF HASTE - {names.char_chicken}" :      904,
    f"CROWN OF GUNS - {names.char_chicken}" :       905,
    f"CROWN OF HATRED - {names.char_chicken}" :     906,
    f"CROWN OF BLOOD - {names.char_chicken}" :      907,
    f"CROWN OF DESTINY - {names.char_chicken}" :    908,
    f"CROWN OF LOVE - {names.char_chicken}" :       909,
    f"CROWN OF LUCK - {names.char_chicken}" :       910,
    f"CROWN OF CURSES - {names.char_chicken}" :     911,
    f"CROWN OF RISK - {names.char_chicken}" :       912,
    f"CROWN OF PROTECTION - {names.char_chicken}" : 913,
}

crown_locations_rebel: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_rebel}" :      1002,
    f"CROWN OF LIFE - {names.char_rebel}" :       1003,
    f"CROWN OF HASTE - {names.char_rebel}" :      1004,
    f"CROWN OF GUNS - {names.char_rebel}" :       1005,
    f"CROWN OF HATRED - {names.char_rebel}" :     1006,
    f"CROWN OF BLOOD - {names.char_rebel}" :      1007,
    f"CROWN OF DESTINY - {names.char_rebel}" :    1008,
    f"CROWN OF LOVE - {names.char_rebel}" :       1009,
    f"CROWN OF LUCK - {names.char_rebel}" :       1010,
    f"CROWN OF CURSES - {names.char_rebel}" :     1011,
    f"CROWN OF RISK - {names.char_rebel}" :       1012,
    f"CROWN OF PROTECTION - {names.char_rebel}" : 1013,
}

crown_locations_horror: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_horror}" :      1102,
    f"CROWN OF LIFE - {names.char_horror}" :       1103,
    f"CROWN OF HASTE - {names.char_horror}" :      1104,
    f"CROWN OF GUNS - {names.char_horror}" :       1105,
    f"CROWN OF HATRED - {names.char_horror}" :     1106,
    f"CROWN OF BLOOD - {names.char_horror}" :      1107,
    f"CROWN OF DESTINY - {names.char_horror}" :    1108,
    f"CROWN OF LOVE - {names.char_horror}" :       1109,
    f"CROWN OF LUCK - {names.char_horror}" :       1110,
    f"CROWN OF CURSES - {names.char_horror}" :     1111,
    f"CROWN OF RISK - {names.char_horror}" :       1112,
    f"CROWN OF PROTECTION - {names.char_horror}" : 1113,
}

crown_locations_rogue: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_rogue}" :      1202,
    f"CROWN OF LIFE - {names.char_rogue}" :       1203,
    f"CROWN OF HASTE - {names.char_rogue}" :      1204,
    f"CROWN OF GUNS - {names.char_rogue}" :       1205,
    f"CROWN OF HATRED - {names.char_rogue}" :     1206,
    f"CROWN OF BLOOD - {names.char_rogue}" :      1207,
    f"CROWN OF DESTINY - {names.char_rogue}" :    1208,
    f"CROWN OF LOVE - {names.char_rogue}" :       1209,
    f"CROWN OF LUCK - {names.char_rogue}" :       1210,
    f"CROWN OF CURSES - {names.char_rogue}" :     1211,
    f"CROWN OF RISK - {names.char_rogue}" :       1212,
    f"CROWN OF PROTECTION - {names.char_rogue}" : 1213,
}

crown_locations_cuz: Dict[str, int] = {
    f"CROWN OF DEATH - {names.char_cuz}" :      1602,
    f"CROWN OF LIFE - {names.char_cuz}" :       1603,
    f"CROWN OF HASTE - {names.char_cuz}" :      1604,
    f"CROWN OF GUNS - {names.char_cuz}" :       1605,
    f"CROWN OF HATRED - {names.char_cuz}" :     1606,
    f"CROWN OF BLOOD - {names.char_cuz}" :      1607,
    f"CROWN OF DESTINY - {names.char_cuz}" :    1608,
    f"CROWN OF LOVE - {names.char_cuz}" :       1609,
    f"CROWN OF LUCK - {names.char_cuz}" :       1610,
    f"CROWN OF CURSES - {names.char_cuz}" :     1611,
    f"CROWN OF RISK - {names.char_cuz}" :       1612,
    f"CROWN OF PROTECTION - {names.char_cuz}" : 1613,
}

crown_location_table: Dict[str, int] = {
    **crown_locations_fish,
    **crown_locations_crystal,
    **crown_locations_eyes,
    **crown_locations_melting,
    **crown_locations_plant,
    **crown_locations_yv,
    **crown_locations_steroids,
    **crown_locations_robot,
    **crown_locations_chicken,
    **crown_locations_rebel,
    **crown_locations_horror,
    **crown_locations_rogue,
    **crown_locations_cuz,
}


location_table: Dict[str, int] = {
    **fish_locations,
    **crystal_locations,
    **eyes_locations,
    **melting_locations,
    **plant_locations,
    **yv_locations,
    **steroids_locations,
    **robot_locations,
    **chicken_locations,
    **rebel_locations,
    **horror_locations,
    **rogue_locations,
    **cuz_locations
}

location_lookup_table: Dict[str, int] = {
    **fish_locations,
    **crystal_locations,
    **eyes_locations,
    **melting_locations,
    **plant_locations,
    **yv_locations,
    **steroids_locations,
    **robot_locations,
    **chicken_locations,
    **rebel_locations,
    **horror_locations,
    **rogue_locations,
    **cuz_locations,
    **goal_locations,
    **crown_location_table
}

lookup_location_to_id = {location: idx for location, idx in location_lookup_table.items() if idx is not None}
